networks:
  punnet:
    driver: ${NETWORKS_DRIVER}

services:

    ### WORKSPACE ###
    workspace:
      hostname: workspace
      build:
        context: ./workspace
        args:
          - TZ=${TZ}
          - PHP_VERSION=${PHP_VERSION}
          - NODE_VERSION=${NODE_VERSION}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      tty: true
      networks:
        - punnet
      ports:
        - 8089:8089
        - 8090:8090

    ### PHP-FPM ###
    php-fpm:
      hostname: php-fpm
      build:
        context: ./php-fpm
        args:
          - TZ=${TZ}
          - PHP_VERSION=${PHP_VERSION}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      expose:
        - 9000
      networks:
        - punnet

    ### NGINX ###
    nginx:
      hostname: nginx
      build:
        context: ./nginx
        args:
          - NGINX_VERSION=${NGINX_VERSION}
          - PHP_UPSTREAM_PORT=${PHP_UPSTREAM_PORT}
          - PHP_UPSTREAM_CONTAINER=${PHP_UPSTREAM_CONTAINER}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      ports:
        - ${NGINX_HOST_HTTP_PORT}:80
        - ${NGINX_HOST_HTTPS_PORT}:443
      depends_on:
        - php-fpm
      networks:
        - punnet
      labels:
        - dev.orbstack.domains=phpmyadmin.local,*.rinvex.local,*.tenant.local,*.dev.local

    ### MYSQL ###
    mysql:
      hostname: mysql
      build:
        context: ./mysql
        args:
          - TZ=${TZ}
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_ROOT_HOST='%'
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - ${MYSQL_PORT}:3306
      networks:
        - punnet

#    ### MARIADB ###
#    mariadb:
#      hostname: mariadb
#      build:
#        context: ./mariadb
#        args:
#          - TZ=${TZ}
#          - MARIADB_VERSION=${MARIADB_VERSION}
#      environment:
#        - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
#      volumes:
#        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
#        - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
#      ports:
#        - ${MARIADB_PORT}:3306
#      networks:
#        - punnet

    ### REDIS ###
    redis:
      hostname: redis
      build:
          context: ./redis
          args:
            - REDIS_VERSION=${REDIS_VERSION}
      volumes:
        - ${DATA_PATH_HOST}/redis:/data
      ports:
        - ${REDIS_PORT}:6379
      networks:
        - punnet

#    ### PORTAINER ###
#    portainer:
#      hostname: portainer
#      build:
#        context: ./portainer
#      volumes:
#        - ${DATA_PATH_HOST}/portainer_data:/data
#        - /var/run/docker.sock:/var/run/docker.sock
#      ports:
#        - ${PORTAINER_PORT}:9000
#      networks:
#        - frontend
#        - punnet
