version: '3'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

services:

    ### WORKSPACE ###
    workspace:
      hostname: workspace
      build:
        context: ./workspace
        args:
          - TZ=${TZ}
          - PHP_VERSION=${PHP_VERSION}
          - NODE_VERSION=${NODE_VERSION}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      tty: true
      networks:
        - frontend
        - backend

    ### PHP-FPM ###
    php-fpm:
      hostname: php-fpm
      build:
        context: ./php-fpm
        args:
          - TZ=${TZ}
          - PHP_VERSION=${PHP_VERSION}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      expose:
        - 9000
      extra_hosts:
        - "dockerhost:${DOCKER_HOST_IP}"
      networks:
        - backend

    ### NGINX ###
    nginx:
      hostname: nginx
      build:
        context: ./nginx
        args:
          - NGINX_VERSION=${NGINX_VERSION}
          - PHP_UPSTREAM_PORT=${PHP_UPSTREAM_PORT}
          - PHP_UPSTREAM_CONTAINER=${PHP_UPSTREAM_CONTAINER}
      volumes:
        - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
        - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
        - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      ports:
        - ${NGINX_HOST_HTTP_PORT}:80
        - ${NGINX_HOST_HTTPS_PORT}:443
      depends_on:
        - php-fpm
      networks:
        - frontend
        - backend

    ### MYSQL ###
    mysql:
      hostname: mysql
      build:
        context: ./mysql
        args:
          - TZ=${TZ}
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - ${MYSQL_PORT}:3306
      networks:
        - backend

    ### REDIS ###
    redis:
      hostname: redis
      build:
          context: ./redis
          args:
            - REDIS_VERSION=${REDIS_VERSION}
      volumes:
        - ${DATA_PATH_HOST}/redis:/data
      ports:
        - ${REDIS_PORT}:6379
      networks:
        - backend

    ### PORTAINER ###
    portainer:
      hostname: portainer
      build:
        context: ./portainer
      volumes:
        - ${DATA_PATH_HOST}/portainer_data:/data
        - /var/run/docker.sock:/var/run/docker.sock
      ports:
        - ${PORTAINER_PORT}:9000
      networks:
        - frontend
        - backend
