networks:
  punnet:
    driver: ${NETWORKS_DRIVER}

services:

    ### WORKSPACE ###
    workspace:
      hostname: workspace
      build:
        context: ./workspace
        args:
          - TZ=${TZ}
          - PHP_VERSION=${PHP_VERSION}
          - NODE_VERSION=${NODE_VERSION}
      volumes:
        - ${PHP_CONFIG_PATH}:/usr/local/etc
        - ${WEB_DATA_PATH}:/var/www:cached
      tty: true
      networks:
        - punnet
      ports:
        - 8089:8089
        - 8090:8090

    ### PHP-FPM ###
    php-fpm:
      hostname: php-fpm
      build:
        context: ./php-fpm
        args:
          - TZ=${TZ}
          - PHP_VERSION=${PHP_VERSION}
      volumes:
        - ${PHP_CONFIG_PATH}:/usr/local/etc
        - ${WEB_DATA_PATH}:/var/www:cached
      expose:
        - ${PHP_UPSTREAM_PORT}
      networks:
        - punnet

    ### NGINX ###
    nginx:
      hostname: nginx
      build:
        context: ./nginx
        args:
          - NGINX_VERSION=${NGINX_VERSION}
          - PHP_UPSTREAM_PORT=${PHP_UPSTREAM_PORT}
          - PHP_UPSTREAM_CONTAINER=${PHP_UPSTREAM_CONTAINER}
      volumes:
        - ${WEB_DATA_PATH}:/var/www:cached
        - ${NGINX_LOG_PATH}:/var/log/nginx/
        - ${NGINX_CONFIG_PATH}:/etc/nginx/
      ports:
        - ${NGINX_HOST_HTTP_PORT}:80
        - ${NGINX_HOST_HTTPS_PORT}:443
      depends_on:
        - php-fpm
      networks:
        - punnet
      labels:
        - dev.orbstack.domains=${LOCAL_DOMAINS}

    ### MYSQL ###
    mysql:
      hostname: mysql
      build:
        context: ./mysql
        args:
          - TZ=${TZ}
          - MYSQL_VERSION=${MYSQL_VERSION}
      environment:
        - MYSQL_ROOT_HOST='%'
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        - ${MYSQL_DATA_PATH}:/var/lib/mysql
        - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - ${MYSQL_PORT}:3306
      networks:
        - punnet

  ### REDIS ###
    redis:
      hostname: redis
      build:
        context: ./redis
        args:
          - REDIS_VERSION=${REDIS_VERSION}
      volumes:
        - ${REDIS_DATA_PATH}:/data
      ports:
        - ${REDIS_PORT}:6379
      networks:
        - punnet

    ### MARIADB ###
    mariadb:
      hostname: mariadb
      build:
        context: ./mariadb
        args:
          - TZ=${TZ}
          - MARIADB_VERSION=${MARIADB_VERSION}
      environment:
        - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      volumes:
        - ${MARIA_DATA_PATH}:/var/lib/mysql
        - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - ${MARIADB_PORT}:3306
      networks:
        - punnet

    ### PORTAINER ###
    portainer:
      hostname: portainer
      build:
        context: ./portainer
      volumes:
        - ${PORTAINER_DATA_PATH}:/data
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - punnet

    ### PROMETHEUS ###
    prometheus:
      hostname: prometheus
      build:
        context: ./prometheus
        args:
          - PROMETHEUS_VERSION=${PROMETHEUS_VERSION}
      volumes:
        - ${PROMETHEUS_CONFIG_PATH}:/etc/prometheus/
        - ${PROMETHEUS_DATA_PATH}:/prometheus
      networks:
        - punnet
#      ports:
#        - ${PROMETHEUS_PORT}:9090
#      labels:
#        - dev.orbstack.domains=prometheus.local

    ### GRAFANA ###
    grafana:
      hostname: grafana
      build:
        context: ./grafana
        args:
          - GRAFANA_VERSION=${GRAFANA_VERSION}
      volumes:
        - ${GRAFANA_DATA_PATH}:/var/lib/grafana
      networks:
        - punnet
#      ports:
#        - ${GRAFANA_PORT}:3000
#      labels:
#        - dev.orbstack.domains=grafana.local
